#pragma config(Sensor, in7,    moGoPo,         sensorPotentiometer)
#pragma config(Sensor, in8,    autonSel,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  lift,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  drive,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  drive1,         sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           fRDrive,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           bLDrive1,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           bRDrive1,      tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mogo,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           bLDrive2,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           bRDrive2,      tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           fLDrive,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          rLift,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "Genral.c"
#include "chassis.c"
#include "manipulators.c"

/*---------------------------------------------------------------------------*/
//                  Pre-Autonomous Functions

void pre_auton()
{
	SensorValue (lift) = 0;
	setPIDValues();
	liftPidEnabled=true
	turnPidEnabled=true;


	bStopTasksBetweenModes = true;


}


//                    Autonomous Task


task autonomous()
{
startTask (drivePid);


if (sensorValue[moGoPo]<100){


}
if (SensorValue[autonSel]<100) {
	setPIDValues();
	startTask (pid);
	liftTarget=-230;
	wait1Msec(1000);
	setMogo(0);
	setChassis(-127,-127);
	setMogo(-127);
	wait1Msec(1000);
	setChassis(0,0);
	setMogo(-10);
	setClaw(127);
	wait1Msec(500);
	setClaw(0);
	setMogo(127);
	wait1Msec(1000);
	setMogo(0);
	liftTarget=-1552;
	wait1Msec(500);
	setChassis(127,127);
	wait1Msec(400);
	setChassis(0,0);
	wait1Msec(1000);
	setChassis(-127,127);
	wait1Msec(600);
	setChassis(0,0);
	setMogo(-127);
	wait1Msec(600);
	setMogo(0);
	setChassis(127,127);
	wait1Msec(350);
	setChassis(0,0);
	setClaw(0);
	setMogo(0);
}



else if (SensorValue[autonSel]<1090){

}


else if (SensorValue[autonSel]<2705){

}

else if (SensorValue[autonSel]<3620){

}
}



//                       User Control Task



task usercontrol()
{
	startTask (pid);
	setPIDValues();
	// User control code here, inside the loop
	int btnToggleState=0;
	int btnPressed=0;
	while (true)
	{
		if (vexRT[Btn8R]==1){
			if (!btnPressed)
			{
				//change state
				btnToggleState=1 - btnToggleState;
				btnPressed=1;
			}
		}
		else{
			btnPressed=0;
		}
		if(btnToggleState)
		{

			setMogo( vexRT[Btn6U]*127 - vexRT[Btn6D]*127 );

			setChassis( vexRT[Ch3], vexRT[Ch2] );


		}
		else
		{


			setMogo( vexRT[Btn6U]*127 - vexRT[Btn6D]*127 );

			setChassis( vexRT[Ch2]*-1, vexRT[Ch3]*-1);


		}

		driverLift();

		driverIntake();

	}
}
